### ISSUE TITLE
MA calculation loops by station rather than logger

### ISSUE THREAD

**Issue by SteveHansonODEQ** [DEQrmichie/odeqcdr#18]
https://github.com/OR-Dept-Environmental-Quality/odeqcdr/blob/29e7944c7df5f46f493b8348fecabd428789590a/R/sumstats.R#L103

Continuous equipment can be daisy chained at the same site to characterize stratification.  This could cause problems to just look at station.  Equipment ID would be better.

**Comment by TravisPritchardODEQ** [comment]
Would an Equipment ID be recycled to a different location within the same import file?

**Comment by SteveHansonODEQ** [comment]
Never, under our procedures.

Steve Hanson
ODEQ Laboratory, WQ Monitoring
Ph: 503.693.5737; Cell: 971.806.2425

**Comment by DEQrmichie** [comment]
Has this been resolved in the new sumstats (sumstats_DQL)?

**Comment by TravisPritchardODEQ** [comment]
No. I can update later today.

**Comment by DEQrmichie** [comment]
Addressed in d24d975
