### ISSUE TITLE
Incorrect Audit Result Field

### ISSUE THREAD

**Issue by SteveHansonODEQ** [DEQrmichie/odeqcdr#29]
The audit result field named Result.Value is not the audit result--instead it is the associated logger result odeqcdr associates with the audit date time.

The actual audit result is in the field named Audit.Result.Value.

The result of this error is that the AWQMS upload template is populated with incorrect data when this function is called as part of the odeqcdr::contin_export function.

https://github.com/OR-Dept-Environmental-Quality/odeqcdr/blob/c88b639363517701d5ab5bfd82ec95823692ddf0/R/cols_audit.R#L14

**Comment by DEQrmichie** [comment]
Addressed in 680d117.  I changed the output column names returned from the dql_precision function so the audit columns match what is in an audit worksheet This should result in the correct columns being pulled when the final audit dataframe is exported.

Here are updated output colums names for dql_precision starting with odeqcdr version 0.20:
Audit.Result.Value -> Result.Value
Audit.Result.Status.ID -> Result.Status.ID
Result.Value -> Logger.Result.Value
Result.datetime -> Logger.datetime

In commit 9096d0f I updated the audit tab column names in shiny to the following:
Result.Value -> Logger.Result.Value
Result.datetime -> Logger.datetime

I also added code so older shiny files that don't have the upated names will stil work.
