### ISSUE TITLE
Right join at end of dql_accuracy() does not ensure correct ordering

### ISSUE THREAD

**Issue by TravisPritchardODEQ** [DEQrmichie/odeqcdr#6]
The right join towards the end of dql_accuracy() does not ensure the ordering of df.results.grade$DQL_acc matches df3.results in the example. This could lead to accDQL not being applied to the results if the ordering of the pre/post audits does not match the ordering of the results. 

Consider replacing with left_join() to 'results', or have function return dataframe for left_join in example sheet.

I will put together a pull request tomorrow that implements the left_join inside of function.

**Comment by DEQrmichie** [comment]
Thanks! I merged your pull request. Addressed in 1fa905b
